export const OPEN_LOADING = 'OPEN_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'
export const INCREASE_STEP = 'INCREASE_STEP'
export const DECREASE_STEP = 'DECREASE_STEP'
export const OPEN_CONFIRM_STAGE = 'OPEN_CONFIRM_STAGE'
export const CLOSE_CONFIRM_STAGE = 'CLOSE_CONFIRM_STAGE'
export const SET_CONFIRM_STAGE = 'SET_CONFIRM_STAGE'
export const ADD_ACCOUNT_INFO = 'ADD_ACCOUNT_INFO'

export const GET_STORE_FETCH = 'GET_STORE_FETCH'
export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS'

export const GET_GMAIL_FETCH = 'GET_GMAIL_FETCH'
export const GET_GMAIL_SUCCESS = 'GET_GMAIL_SUCCESS'

export const POST_REGISTER_FETCH = 'POST_REGISTER_FETCH'
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS'
